<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SizesTableSeeder extends Seeder
{
    public function run()
    {
        $sizes = [
            ['width' => 3.5, 'height' => 2, 'unit' => 'inches'],
            ['width' => 3.5, 'height' => 8.5, 'unit' => 'inches'],
            ['width' => 4, 'height' => 6, 'unit' => 'inches'],
            ['width' => 5.5, 'height' => 8.5, 'unit' => 'inches'],
            ['width' => 6, 'height' => 24, 'unit' => 'inches'],
            ['width' => 6, 'height' => 32, 'unit' => 'inches'],
            ['width' => 6, 'height' => 36, 'unit' => 'inches'],
            ['width' => 8.5, 'height' => 11, 'unit' => 'inches'],
            ['width' => 8, 'height' => 8, 'unit' => 'inches'],
            ['width' => 11, 'height' => 17, 'unit' => 'inches'],
            ['width' => 12, 'height' => 12, 'unit' => 'inches'],
            ['width' => 12, 'height' => 16, 'unit' => 'inches'],
            ['width' => 12, 'height' => 18, 'unit' => 'inches'],
            ['width' => 12, 'height' => 24, 'unit' => 'inches'],
            ['width' => 12, 'height' => 36, 'unit' => 'inches'],
            ['width' => 12, 'height' => 48, 'unit' => 'inches'],
            ['width' => 12, 'height' => 60, 'unit' => 'inches'],
            ['width' => 12, 'height' => 72, 'unit' => 'inches'],
            ['width' => 16, 'height' => 20, 'unit' => 'inches'],
            ['width' => 18, 'height' => 12, 'unit' => 'inches'],
            ['width' => 18, 'height' => 24, 'unit' => 'inches'],
            ['width' => 20, 'height' => 24, 'unit' => 'inches'],
            ['width' => 20, 'height' => 30, 'unit' => 'inches'],
            ['width' => 22, 'height' => 28, 'unit' => 'inches'],
            ['width' => 24, 'height' => 24, 'unit' => 'inches'],
            ['width' => 24, 'height' => 32, 'unit' => 'inches'],
            ['width' => 24, 'height' => 36, 'unit' => 'inches'],
            ['width' => 24, 'height' => 48, 'unit' => 'inches'],
            ['width' => 24, 'height' => 60, 'unit' => 'inches'],
            ['width' => 24, 'height' => 72, 'unit' => 'inches'],
            ['width' => 30, 'height' => 84, 'unit' => 'inches'],
            ['width' => 31.5, 'height' => 78.75, 'unit' => 'inches'],
            ['width' => 31.5, 'height' => 81, 'unit' => 'inches'],
            ['width' => 31.5, 'height' => 90, 'unit' => 'inches'],
            ['width' => 32, 'height' => 48, 'unit' => 'inches'],
            ['width' => 33.5, 'height' => 78.75, 'unit' => 'inches'],
            ['width' => 35.43, 'height' => 78.75, 'unit' => 'inches'],
            ['width' => 35.43, 'height' => 81, 'unit' => 'inches'],
            ['width' => 35.43, 'height' => 90, 'unit' => 'inches'],
            ['width' => 36, 'height' => 12, 'unit' => 'inches'],
            ['width' => 36, 'height' => 36, 'unit' => 'inches'],
            ['width' => 36, 'height' => 48, 'unit' => 'inches'],
            ['width' => 36, 'height' => 60, 'unit' => 'inches'],
            ['width' => 36, 'height' => 72, 'unit' => 'inches'],
            ['width' => 36, 'height' => 84, 'unit' => 'inches'],
            ['width' => 39.37, 'height' => 78.75, 'unit' => 'inches'],
            ['width' => 39.37, 'height' => 81, 'unit' => 'inches'],
            ['width' => 39.37, 'height' => 90, 'unit' => 'inches'],
            ['width' => 47.5, 'height' => 48.75, 'unit' => 'inches'],
            ['width' => 47.5, 'height' => 78.75, 'unit' => 'inches'],
            ['width' => 47.5, 'height' => 81, 'unit' => 'inches'],
            ['width' => 47.5, 'height' => 90, 'unit' => 'inches'],
            ['width' => 48, 'height' => 12, 'unit' => 'inches'],
            ['width' => 48, 'height' => 48, 'unit' => 'inches'],
            ['width' => 48, 'height' => 60, 'unit' => 'inches'],
            ['width' => 48, 'height' => 72, 'unit' => 'inches'],
            ['width' => 48, 'height' => 84, 'unit' => 'inches'],
            ['width' => 48, 'height' => 96, 'unit' => 'inches'],
            ['width' => 60, 'height' => 12, 'unit' => 'inches'],
            ['width' => 60, 'height' => 24, 'unit' => 'inches'],
            ['width' => 60, 'height' => 36, 'unit' => 'inches'],
            ['width' => 60, 'height' => 48, 'unit' => 'inches'],
            ['width' => 60, 'height' => 60, 'unit' => 'inches'],
            ['width' => 72, 'height' => 12, 'unit' => 'inches'],
            ['width' => 72, 'height' => 24, 'unit' => 'inches'],
            ['width' => 72, 'height' => 36, 'unit' => 'inches'],
            ['width' => 72, 'height' => 48, 'unit' => 'inches'],
            ['width' => 72, 'height' => 58, 'unit' => 'inches'],
            ['width' => 72, 'height' => 60, 'unit' => 'inches'],
            ['width' => 72, 'height' => 72, 'unit' => 'inches'],
            ['width' => 84, 'height' => 12, 'unit' => 'inches'],
            ['width' => 84, 'height' => 24, 'unit' => 'inches'],
            ['width' => 84, 'height' => 36, 'unit' => 'inches'],
            ['width' => 84, 'height' => 48, 'unit' => 'inches'],
            ['width' => 84, 'height' => 58, 'unit' => 'inches'],
            ['width' => 84, 'height' => 60, 'unit' => 'inches'],
            ['width' => 84, 'height' => 72, 'unit' => 'inches'],
            ['width' => 84, 'height' => 84, 'unit' => 'inches'],
            ['width' => 96, 'height' => 12, 'unit' => 'inches'],
            ['width' => 96, 'height' => 24, 'unit' => 'inches'],
            ['width' => 96, 'height' => 36, 'unit' => 'inches'],
            ['width' => 96, 'height' => 48, 'unit' => 'inches'],
            ['width' => 96, 'height' => 51, 'unit' => 'inches'],
            ['width' => 96, 'height' => 60, 'unit' => 'inches'],
            ['width' => 96, 'height' => 72, 'unit' => 'inches'],
            ['width' => 108, 'height' => 12, 'unit' => 'inches'],
            ['width' => 108, 'height' => 24, 'unit' => 'inches'],
            ['width' => 108, 'height' => 36, 'unit' => 'inches'],
            ['width' => 108, 'height' => 48, 'unit' => 'inches'],
            ['width' => 108, 'height' => 60, 'unit' => 'inches'],
            ['width' => 108, 'height' => 72, 'unit' => 'inches'],
            ['width' => 120, 'height' => 12, 'unit' => 'inches'],
            ['width' => 120, 'height' => 24, 'unit' => 'inches'],
            ['width' => 120, 'height' => 36, 'unit' => 'inches'],
            ['width' => 120, 'height' => 48, 'unit' => 'inches'],
            ['width' => 120, 'height' => 60, 'unit' => 'inches'],
            ['width' => 120, 'height' => 72, 'unit' => 'inches'],
            ['width' => 144, 'height' => 12, 'unit' => 'inches'],
            ['width' => 144, 'height' => 24, 'unit' => 'inches'],
            ['width' => 144, 'height' => 36, 'unit' => 'inches'],
            ['width' => 144, 'height' => 48, 'unit' => 'inches'],
            ['width' => 144, 'height' => 60, 'unit' => 'inches'],
            ['width' => 144, 'height' => 72, 'unit' => 'inches'],
        ];

        // Insert sizes into the sizes table
        DB::table('sizes')->insert(array_map(function ($size) {
            return array_merge($size, [
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }, $sizes));
    }
}
